binds:
  - port: 3000
    listeners:
      - routes:
          - matches:
              - path:
                  exact: /mcp
              - path:
                  exact: /.well-known/oauth-protected-resource/mcp
            policies:
              cors:
                allowOrigins: ["*"]
                allowHeaders: [mcp-protocol-version, content-type, authorization]
                exposeHeaders: ["Mcp-Session-Id"]
            backends:
              - mcp:
                  failureMode: failOpen
                  prefixMode: never
                  targets:
                    - name: google
                      policies:
                        backendAuth:
                          passthrough: {}
                      mcp:
                        host: http://google-workspace:8080/mcp
